language: ruby

install:
  - wget https://packages.chef.io/files/stable/chef/12.15.19/ubuntu/12.04/chef_12.15.19-1_amd64.deb
  - sudo dpkg -i chef_12.15.19-1_amd64.deb
  - bundle install

rvm:
  - 2.3.2
