language: bash

install:
  - sudo apt-get update
  - sudo apt-get install axel
  - sudo apt-get install linux-headers-generic
  - sudo apt-get install virtualbox virtualbox-dkms
  - sudo dpkg-reconfigure virtualbox-dkms
  - sudo dpkg-reconfigure virtualbox
  - sudo apt-get --reinstall install virtualbox-dkms

script:
  - bash packer-build.sh
